spring:
  application:
    name: eureka

server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
    appname: eureka
  client:
    serviceUrl:
      defaultZone: http://eureka1:8761/eureka/,http://eureka3:8763/eureka/