server:
  port: 3000

eureka:
  instance:
      hostname: localhost
  server:
      # 关闭自我保护机制
      enable-self-preservation: false
      # 每隔10s扫描服务列表，移除失效服务
      eviction-interval-timer-in-ms: 10000
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/