server:
  port: 3001
spring:
  application:
    name: demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:3000/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        appname: demo

