server:
  port: 80
spring:
  application:
    name: kiiik-zuul
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 111111
    url: jdbc:mysql://localhost:3306/system?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@localhost:8888/eureka/
    instance:
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
        appname: kiiik-zuul
zuul: 
  routes: 
    service0: #设置敏感头部信息。 Cookie/Set-Cookie 
      sensitive-headers: Authorization
      path: /api1/**
      #url: http://localhost:8080/
      service-id: DEMO-1
    service1:
      path: /api2/**
      service-id: DEMO-2
      #url: http://localhost:8090/
      sensitive-headers: Authorization